/* International Morse Code */
/* coding: the last 5 bits are an offset into the crypt, the first 3 bits the length of the code */
/* generated by gencw.py, don't modify */
#define CWSTARTMASK (0x1f)
#define CWSIZEMASK (0x07)
#define CWSIZESHIFT (0x05)
char *crypt=".....-----....-.-.--..--..-...--.- ";
char *plain="+.,:?-/=@!0123456789abcdefghijklmnopqrstuvwxyz";
char *code="\xad\xcd\xd2\xc7\xd4\xc9\xb7\xba\xcb\xcb\xa5\xa4\xa3\xa2\xa1\xa0\xa9\xa8\xa7\xa6\x44\x89\x8e\x69\x20\x8c\x68\x80\x40\x84\x6e\x99\x45\x49\x65\x91\x9e\x6d\x60\x25\x63\x82\x64\x93\x90\x88";
